version: '3.9'

services:
  order-service:
    build:
      context: ./OrderService
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      OTEL_SERVICE_NAME: "ORDER-SERVICE"
      OTEL_TRACES_EXPORTER: "jaeger, zipkin"
      OTEL_EXPORTER_JAEGER_ENDPOINT: "http://jaeger:14250"
      OTEL_EXPORTER_ZIPKIN_ENDPOINT: "http://zipkin:9411/api/v2/spans"
      OTEL_METRICS_EXPORTER: "logging"
      OTEL_LOGS_EXPORTER: "logging"
      DB_HOST: "micro-db"
      CONFIG_SERVER_URL: "http://config-server:9296"
    depends_on:
      - micro-db
      - config-server
      - service-registry
    networks:
      - default

  product-service:
    build:
      context: ./ProductService
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      OTEL_SERVICE_NAME: "PRODUCT-SERVICE"
      OTEL_TRACES_EXPORTER: "jaeger, zipkin"
      OTEL_EXPORTER_JAEGER_ENDPOINT: "http://jaeger:14250"
      OTEL_EXPORTER_ZIPKIN_ENDPOINT: "http://zipkin:9411/api/v2/spans"
      OTEL_METRICS_EXPORTER: "logging"
      OTEL_LOGS_EXPORTER: "logging"
      DB_HOST: "micro-db"
      CONFIG_SERVER_URL: "http://config-server:9296"
    depends_on:
      - micro-db
      - config-server
      - service-registry
    networks:
      - default

  payment-service:
    build:
      context: ./PaymentService
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      OTEL_SERVICE_NAME: "PAYMENT-SERVICE"
      OTEL_TRACES_EXPORTER: "jaeger, zipkin"
      OTEL_EXPORTER_JAEGER_ENDPOINT: "http://jaeger:14250"
      OTEL_EXPORTER_ZIPKIN_ENDPOINT: "http://zipkin:9411/api/v2/spans"
      OTEL_METRICS_EXPORTER: "logging"
      OTEL_LOGS_EXPORTER: "logging"
      DB_HOST: "micro-db"
      CONFIG_SERVER_URL: "http://config-server:9296"
    depends_on:
      - micro-db
      - config-server
      - service-registry
    networks:
      - default

  config-server:
    build:
      context: ./ConfigServer
      dockerfile: Dockerfile
    image: config-server:latest
    environment:
      EUREKA_SERVICE_ADDRESS: "http://service-registry:8761/eureka"
      OTEL_SERVICE_NAME: "CONFIG-SERVER"
      OTEL_TRACES_EXPORTER: "jaeger, zipkin"
      OTEL_EXPORTER_JAEGER_ENDPOINT: "http://jaeger:14250"
      OTEL_EXPORTER_ZIPKIN_ENDPOINT: "http://zipkin:9411/api/v2/spans"
      OTEL_METRICS_EXPORTER: "logging"
      OTEL_LOGS_EXPORTER: "logging"
    ports:
      - "9296:9296"
    networks:
      - default
    depends_on:
      - service-registry

  micro-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql  # Named volume for database persistence
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - default

  service-registry:
    build:
      context: ./service-registry
      dockerfile: Dockerfile
    environment:
      OTEL_SERVICE_NAME: "SERVICE-REGISTRY"
      OTEL_TRACES_EXPORTER: "jaeger, zipkin"
      OTEL_EXPORTER_JAEGER_ENDPOINT: "http://jaeger:14250"
      OTEL_EXPORTER_ZIPKIN_ENDPOINT: "http://zipkin:9411/api/v2/spans"
      OTEL_METRICS_EXPORTER: "logging"
      OTEL_LOGS_EXPORTER: "logging"
    ports:
      - "8761:8761"
    networks:
      - default

#  collector:
#    container_name: collector
#    image: otel/opentelemetry-collector-contrib:0.91.0
#    command:
#      - --config=/etc/otelcol-contrib/otel-collector.yml
#    volumes:
#      - ./docker/collector/otel-collector.yml:/etc/otelcol-contrib/otel-collector.yml
#    ports:
#      - "4317" # OTLP gRPC receiver
#      - "8889" # Prometheus exporter metrics
#    depends_on:
#      - loki
#      - jaeger-all-in-one
#      - zipkin-all-in-one
#     # - tempo
#    networks:
#      - default
  jaeger-all-in-one:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "4317"
    networks:
      - default

  zipkin-all-in-one:
    container_name: zipkin
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - "9411:9411"
    networks:
      - default


networks:
  default:
    driver: bridge

volumes:
  mysql-data:
