receivers:
  otlp:
    protocols:
      http:

exporters:
  jaeger:
    endpoint: "http://jaeger:14268/api/traces"

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [jaeger]
