name: Build and Push Docker Images

on:
  push:
    branches:
      - master  # Change this to your main branch
  pull_request:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

    strategy:
      matrix:
        service: [ConfigServer, OrderService, PaymentService, ProductService, service-registry]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}

      - name: Build Docker image for ${{ matrix.service }}
        run: |
          cd ${{ matrix.service }}
          docker build -t ${{ env.DOCKER_HUB_USERNAME }}/${{ matrix.service }}-shop-app-microservice:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ env.DOCKER_HUB_USERNAME }}/${{ matrix.service }}-shop-app-microservice:latest
